#!/usr/bin/env python

import sys, os
import signal
from fuzzer import fuzzer

sat_fuzzer = None

def sigterm_handler(signal, frame):
    global sat_fuzzer
    sat_fuzzer.shutdown()
    sys.exit(0)

if len(sys.argv) < 3:
    print("Usage: ./fuzz-sat <path_to_sut_source> <path_to_inputs_dir> [<seed>]")
    sys.exit(1)

if not os.path.isdir(sys.argv[1]) or not os.path.isdir(sys.argv[2]):
    print("Error: please provide valid paths to the SUT source and inputs directory")
    sys.exit(1)


# Register signal handlers for shutdown
signal.signal(signal.SIGTERM, sigterm_handler)
signal.signal(signal.SIGINT, sigterm_handler)
signal.signal(signal.SIGQUIT, sigterm_handler)

# Fuzz
sat_fuzzer = fuzzer.Fuzzer(sys.argv)
sat_fuzzer.start()


